# To execute :
# ansible-playbook installApach.yml  -i inventory.yaml --private-key /Users/KaiqiYang/Documents/MasterCourse/Cloud/Assignment2/cloud.key

---
- hosts: dbs
  vars:
    http_port: 80
    max_clients: 200
  # remote_user: root
  tasks:
      - name: terminate other jobs
        shell: set -e

      - name: update packages
        sudo: yes
        shell: apt-get update || true

      - name: install dependencies
        sudo: yes
        shell: apt-get --no-install-recommends -y install build-essential pkg-config runit erlang libicu-dev libmozjs185-dev libcurl4-openssl-dev

      - name: download the couchdb file 
        # shell: wget http://apache-mirror.rbc.ru/pub/apache/couchdb/source/2.0.0/apache-couchdb-2.0.0.tar.gz
        get_url:
          url: http://apache-mirror.rbc.ru/pub/apache/couchdb/source/2.0.0/apache-couchdb-2.0.0.tar.gz
          dest: ./

      - name: uncompress the tar
        shell: tar -xvzf apache-couchdb-2.0.0.tar.gz

        # - unarchive:
        #     src: foo.tgz
        #     dest: /var/lib/foo
      - name: cd to the directory and install
        shell: cd apache-couchdb-2.0.0 && ./configure && make release
        # command: chdir=apache-couchdb-2.0.0/

      # - name: install couchdb
      #   shell: ./configure && make release

    # - name: Update all packages to the latest version
    #   sudo: yes
    #   shell: deploycouchdb.sh >> scriptOutput.txt

    # - name: Update repositories cache and install "python-pip" package
    #   sudo: yes
    #   apt:
    #     name: python-pip
    #     update_cache: yes
    
    # - name: Remove "pip" package
    #   sudo: yes
    #   apt:
    #     name: python-pip
    #     state: absent

    # - name: install pip
    #   sudo: yes
    #   apt: 
    #     name: python-pip
    #     state: present
    
    # - name: Update repositories cache and install "couchdb-bin" package
    #   sudo: yes
    #   apt:
    #     name: couchdb-bin
    #     update_cache: yes

    # - name: Remove "couchdb" package
    #   sudo: yes
    #   apt:
    #     name: couchdb
    #     state: absent

    # - name: Remove "couchdb-bin" package
    #   sudo: yes
    #   apt:
    #     name: couchdb-bin
    #     state: absent
    
    # - name: Remove "couchdb-common" package
    #   sudo: yes
    #   apt:
    #     name: couchdb-common
    #     state: absent

    # # sudo apt install couchdb-bin
    # - name: install couchdb-bin
    #   sudo: yes
    #   apt: 
    #     name: couchdb-bin
    #     state: present

    # - name: install couchdb
    #   sudo: yes
    #   apt: 
    #     name: couchdb
    #     state: present

    # # sudo apt install upstart
    # - name: install upstart
    #   sudo: yes
    #   apt:
    #     name: upstart
    #     state: present

    # - name: install yum
    #   sudo: yes
    #   apt:
    #     name: yum
    #     state: present


...