# To execute :
# ansible-playbook InstallCouchdb.yml  -i ansibleinventory.yaml --private-key /Users/KaiqiYang/Documents/MasterCourse/Cloud/Assignment2/cloud.key
---
- hosts: server
  vars:
    http_port: 80
    max_clients: 200
  tasks:
      - name: stop all
        ignore_errors: True
        shell: pm2 delete TweetsSummary && pm2 delete TweetsAnalysis

      - name: remove old version
        ignore_errors: True
        sudo: yes
        shell: rm -r comp90024-australiacityanalytics

      - name: Install the package "git"
        sudo: yes
        apt:
          name: git
          state: present

      - name: Get the source code from git
        shell: git clone https://kaiqiypublic:kaiqiypublicpw@bitbucket.org/xingh1/comp90024-australiacityanalytics.git

      - name: give pemission
        sudo: yes
        shell: chmod +x comp90024-australiacityanalytics/tweetsanalysis/CreateView/MapReduceFunctions/run.sh

      - name: run
        ignore_errors: True
        shell: cd comp90024-australiacityanalytics/tweetsanalysis/CreateView/MapReduceFunctions && ./run.sh
...


